### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by Sharif90**
Test Branching
I updated Reservation class variables  
Please review and pull

### CODE REVIEW

**Comment by baselqyqony** [comment]
changes reviewed and merged

**Comment by ahreda** [comment]
The updating is rewired and it is ok

**Comment by ZsoltToth** [comment]
It seems to be OK.

**Comment by ZsoltToth** [comment]
In the ReservationManagerService you have defined two methods that are already defined in other services. This service should be reworked in the future.

**Pull request merged**
